### ISSUE TITLE
Be able to use import lifecast in existing project

### ISSUE THREAD

**Issue by remmel** [fbriggs/lifecast_public#5]
Currently, this is difficult to use lifecast in existing THREE js project because :

- depend (commited) to THREE.js and specific version (If you use it in existing project, THREE js will be loaded multiple time)
- cannot access to LifecastVideoPlayer or HTMLVideoElement
- code related with player interaction is in same class than the one creating the Mesh / Object3D

I'll push some PR in order to make it easy to be imported

**Comment by remmel** [comment]
FYI here is some code to be able to use your lib as CDN (works) and display images in npm/cdn/included mode - however when using the lib as npm or cdn, texture might not be displayed in VR https://github.com/remmel/lifecast_public/tree/cdn

```
<script async src="https://unpkg.com/es-module-shims@1.6.3/dist/es-module-shims.js"></script>
<script type="importmap-shim" src="https://cdn.jsdelivr.net/gh/remmel/lifecast_public@cdn/web/importmap.json"></script>
<!--<script type="importmap-shim" src="importmap.json"></script>-->

<script type="module-shim">
  import * as LifecastVideoPlayer from 'lifecast';
  LifecastVideoPlayer.init({_media_url: "https://cdn.jsdelivr.net/gh/remmel/lifecast_public@cdn/web/media/000000.mp4"});
</script>

```

**Comment by fbriggs** [comment]
@remmel thanks for your work on this. One suggestion for a better chance with the PR is to avoid package managers and minimize external dependencies.

**Comment by remmel** [comment]
That issue can be closed thanks to https://github.com/fbriggs/lifecast_public/pull/12 and threejs can be updated if using webpack with that configuration :
`webpack.config.cjs`:
```
  resolve: {
    alias: {
      './three149.module.min.js': 'three',
    }
  },
```
It will also avoid multiple THREE being imported
